name: Build Concorde

on:
  workflow_dispatch:

jobs:
  buildconcorde:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: build concorde (Linux)
      run: cd binaries/scripts && ./build-concorde-linux.sh
      if: matrix.os == 'ubuntu-latest'
    - name: build concorde (macOS)
      run: |
        cd binaries/scripts
        ./build-concorde-mac-x86_64.sh
        ./build-concorde-mac-arm64.sh
      if: matrix.os == 'macos-latest'
        
